(function () {

  DataManager._databaseFiles.push(
    { name: '$Yom1', src: '../mes/Yom1.json'},
    { name: '$Yom2', src: '../mes/Yom2.json'},
    { name: '$Yom3', src: '../mes/Yom3.json'},
    { name: '$Yom4', src: '../mes/Yom4.json'},
    { name: '$Bbiri', src: '../mes/Bbiri.json'},
    { name: '$Sissin', src: '../mes/Sissin.json'},
    { name: '$Scene', src: '../mes/Scene.json'},
    { name: '$Ona', src: '../mes/Ona.json'},
    { name: '$fera', src: '../mes/fera.json'},
    { name: '$kikan', src: '../mes/kikan.json'},
    { name: '$kikan2', src: '../mes/kikan2.json'},
    { name: '$Rape', src: '../mes/Rape.json'},
    { name: '$Zayaku', src: '../mes/Zayaku.json'},
    { name: '$Hantei', src: '../mes/Hantei.json'},
    { name: '$Act1_1', src: '../mes/Act1_1.json'},
    { name: '$Act1_2', src: '../mes/Act1_2.json'},
    { name: '$Act2_1', src: '../mes/Act2_1.json'},
    { name: '$Act2_2', src: '../mes/Act2_2.json'},
    { name: '$Act3_1', src: '../mes/Act3_1.json'},
    { name: '$Act3_2', src: '../mes/Act3_2.json'},
    { name: '$Act4_1', src: '../mes/Act4_1.json'},
    { name: '$Act4_2', src: '../mes/Act4_2.json'},
    { name: '$Act5_1', src: '../mes/Act5_1.json'},
    { name: '$Act5_2', src: '../mes/Act5_2.json'},
    { name: '$Act6_1', src: '../mes/Act6_1.json'},
    { name: '$Act6_2', src: '../mes/Act6_2.json'},
    { name: '$Act7_1', src: '../mes/Act7_1.json'},
    { name: '$Act7_2', src: '../mes/Act7_2.json'},
    { name: '$Act8_1', src: '../mes/Act8_1.json'},
    { name: '$Act8_2', src: '../mes/Act8_2.json'},
    { name: '$Act9_1', src: '../mes/Act9_1.json'},
    { name: '$Act9_2', src: '../mes/Act9_2.json'},
    { name: '$Yom1_8_9', src: '../mes/Yom1_8_9.json'},
    { name: '$Yom2_8_9', src: '../mes/Yom2_8_9.json'},
    { name: '$Yom3_8_9', src: '../mes/Yom3_8_9.json'},
    { name: '$Bbiri_8_9', src: '../mes/Bbiri_8_9.json'},
    { name: '$Sissin_8_9', src: '../mes/Sissin_8_9.json'},
    { name: '$Scene_8_9', src: '../mes/Scene_8_9.json'},
    { name: '$Ona_8_9', src: '../mes/Ona_8_9.json'},
    { name: '$fera_8_9', src: '../mes/fera_8_9.json'},
    { name: '$kikan_8_9', src: '../mes/kikan_8_9.json'},
    { name: '$Rape_8_9', src: '../mes/Rape_8_9.json'},
    { name: '$Zayaku_8_9', src: '../mes/Zayaku_8_9.json'},
    { name: '$Hantei_8_9', src: '../mes/Hantei_8_9.json'},
    { name: '$Act10_1', src: '../mes/Act10_1.json'},
    { name: '$Act11_1', src: '../mes/Act11_1.json'},
    { name: '$Act12_1', src: '../mes/Act12_1.json'}
  );

})();